repos:
  - repo: local
    hooks:
      - id: rust-check
        name: Rust Check
        entry: make check
        language: system
        files: \.rs$
        pass_filenames: false

      - id: rust-fmt
        name: Rust Format
        entry: make format
        language: system
        files: \.rs$
        pass_filenames: false

      - id: rust-clippy
        name: Rust Clippy
        entry: make lint
        language: system
        files: \.rs$
        pass_filenames: false