name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build WebAssembly (Release)
        run: make build-release

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium firefox webkit

      - name: Verify test fixtures exist
        run: |
          ls -la tests/e2e/fixtures/
          test -f tests/e2e/fixtures/with-metadata.jpg

      - name: Run E2E tests
        run: npm run test:e2e
        env:
          CI: true

      - name: Upload test results on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      - name: Upload test screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-screenshots
          path: test-results/
          retention-days: 7

  test-mobile:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build WebAssembly (Release)
        run: make build-release

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium webkit

      - name: Verify test fixtures exist
        run: |
          ls -la tests/e2e/fixtures/
          test -f tests/e2e/fixtures/with-metadata.jpg

      - name: Run Mobile E2E tests
        run: npx playwright test tests/e2e/mobile.spec.ts
        env:
          CI: true

      - name: Upload mobile test results on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: mobile-test-results
          path: playwright-report/
          retention-days: 7